### ISSUE TITLE
Support for priority / preload

### ISSUE THREAD

**Issue by markomitranic** [coreyward/sanity-image#31]
Hey there! I discovered this sweet wrapper, from the Sanity YouTube clip, thank you so much for making a relatively sane approach to marrying the two :) 

I'm lacking a property, which the native Next Image supports https://nextjs.org/docs/pages/api-reference/components/image#priority

I'm not entirely sure how they do it. Is there any chance for us to get an equivalent? It is very useful for loaders, slideshow[0], logos, menu items etc.

**Comment by coreyward** [comment]
All Next.js is doing here is adding a `rel="preload"` tag to the `<head>` that is pre-configured for the image. You can read more about [how that works here](https://web.dev/preload-responsive-images/#imagesrcset-and-imagesizes).

While doing something like this is possible, it's not something I think is merited here for a couple reasons:

1. Preloading only makes sense in cases where the HTML sent back from the server does not have the necessary instructions for the browser on where to find the appropriate image. 
2. Preloading requires manipulation of the `<head>`. The approach for doing this (performantly) depends on the framework used. Since Sanity Image is general purpose, framework-specific approaches are something I am avoiding.

In most cases, if you're using SanityImage with Next.js, you're doing server-side rendering anyways. In this scenario putting `loading="eager"` on top-of-fold images will provide most of the benefit of using preloading. Both require the DOM to be parsed before the browser can move onto fetching the image even. If you are not setting a `sizes` attribute, using `preload` is actually worse—you *have to* know the specific variant that will be loaded or you wind up loading extraneous data that is thrown away.

If you have a case where you are dynamically rendering the image client side, you probably don't know what image you need to load server-side anyways, and client-side insertion of a `rel="preload"` tag doesn't have much impact. If you are trying to preload the next image in a carousel that does not write all items to the DOM, preloading manually (`img = new Image(); img.src = "url"`) is an option, or you can use the `buildSrc` and `buildSrcSet` routines exported by Sanity Image to assemble the arguments for your own `rel="preload"` tag.

You mentioned logos and menus—again, those are likely served by just putting the content in your HTML like normal and letting the browser’s [preload scanner](https://web.dev/preload-scanner/) do the job it is optimized for. Explicit `rel="preload"` is intended for specific cases that affect LCP and CLS.

As a final note w/r/t `next/image`: taking advantage of the optimizations it provides requires a lot of configuration effort. It's easy to do more harm than good if you drop it on the page and pass it some props. You really need to tune the dimensions of your images based on presentation, prevent your loader func from upscaling the image, provide a sensible srcset (sufficient distance between sizes, but also relevant sizes, and also not duplicates), and add a `sizes` attribute matching your presentation. From what I've witnessed, this is much easier said than done—every website I've checked has it doing something wrong, from prioritizing low-value images to upscaling source images to generating needlessly large images and more. Adding preloading only magnifies these issues.

**Comment by markomitranic** [comment]
Thank you for a wonderful response @coreyward just for context, this specific case included assets visible only in a megamenu, so the browser preload detector doesn't figure em out :P preload is the only way to actually get them to eagerly load before we open the menu, so that we don't get flashes.

For future reference and people googling this.....

## What I ended up using is:

```ts
ReactDOM.preload(imageUrl, { as: "image" as "script" });
```

I just pop it into one of my components, works with both server and client.
I have yet to figure out how to get the actual URL :P I use `@sanity/image-url` to get the url, but there is no point in that because if the URL varies slightly from what `coreyward/sanity-image` produces, we just cached the wrong asset...

## A sidenote about srcsets:
Next has no built-in way to manually edit the head with `appRouter`, yet. It has been discussed here: https://github.com/vercel/next.js/issues/43134 That is why we manually use ReactDom, which is also what they use internally.

As they pointed out, the `as: "image"` is actually not supported by `react-dom` because Safari doesn't support `srcsets` on these head tags. So, it is important to not try and provide srcsets. Then we have to either prevent `coreyward/sanity-image` from using srcsets, or preload all the srcsets -.- 

this is all a pain in the ass at this point, so I quit trying. In reality there is little use for this with Sanity images, its is very much tied to the behaviour of the html... I decided to host the image as a next asset, without any srcsets and just preload it manually at max size. Which meant I have to also make sure to optimise it.

**Comment by coreyward** [comment]
Out of curiosity, is the menu HTML written to the DOM server side? If so, removing `loading=lazy` from the `img` tag should be enough to let the browser handle it. But perhaps if they're large images on slow connections that's not sufficient.

In any case, the `buildSrc` export from SanityImage will generate the value used for `src` if supplied the same inputs. Same for `buildSrcSet` for the `srcset` value. Check the `urlBuilder.test.ts` file to get an idea on usage. It's still not possible to predict server-side which URL will be used by the browser with these, but you can at least avoid the additional import of @sanity/image-url, which behaves differently and won't avoid upscaling images.

**Comment by markomitranic** [comment]
@coreyward That is a good point, they are client side, unfortunately. So setting eager loading won't actually make the browser do it, as it is not aware of them on page load :/ Thats why I started looking into manually preloading em, there is a way to move them to the server, but it is a bit convoluted, so preloading seemed easier.

Even tho this is very tied into the template, and thus may be  better treated as a static asset, I really liked the idea of serving it from Sanity for 2 reasons:
1. Editable in sanity, duh.
2. I love how this lib works with size calculation, loading and blurs, and wanted to use it.

Thanks for the tip about `buildSrc`! I was thinking about if I could use it, but I didn't know how to actually employ that :D I'll use that for sure! I'll post back when I have a solution!

**Comment by markomitranic** [comment]
@coreyward Tried out all approaches and I have a correction to make :) 

An image will be preloaded, if `eager` is set, regardless of if it was rendered or not. The only important thing is that it is present in the DOM. Regardless of if it is client or server component. Nothing eureka there. The issue with my specific code was that a couple of layers above these components, I've had a portal. Specifically `headlessui`'s `Transition` - which ends up never placing the elements into the DOM.

This means that I do have to trigger a preload outside of the component. At least that was fairly easy, so I just rendered a couple of SanityImage components with eager loading, above my portal, with display none. Since the params are the same, and the client calculates the URL in both cases, we get a preloaded image, while completely relying on the browser's decisionmaking :) As you yourself have said we should. 

Thanks and sorry for wasting a bit of your time, as this is in no way related to your library. I did, however learn something new! - `buildSrc` is super easy to use and i can replace usages of `@sanity/image-url` that i was forced to have in my metadata functions, where we never render anything but just need a string url for OG tags. I'd prefer to rely on a single library for both.
