### ISSUE TITLE
Pure function evaluates `useState` for no reason, when using `buildSrc`

### ISSUE THREAD

**Issue by markomitranic** [coreyward/sanity-image#33]
Importing `sanity-image` in any shape, in my files will, of course, load the whole exported module. Some of the parts fo the exported module use client component hooks like `useState`, I am making a wild guess that it is the blur+load logic.

In any case, this makes the whole package unusable in server components, something that React (and NextJS) are heavily leaning into. Now, let's look at it in two use cases:

1. Somehow, magically making the package work as part of server components would be great, as the html output would contain a fully baked img tag. This will, however screw up the loading (i assume)? So it's a no-go.
2. Since the above is not feasible, it would be amazing to extract some of the functional parts into a sub module, for example `buildSrc` function can easily live in its own file, as it doesn't require react hooks to work. 

Any thoughts?

**Comment by coreyward** [comment]
**NOTE:** For context for anybody poking about issues, this is in reference to the (widely maligned) Next.js App Router, which relies on the bleeding edge Server Components feature in React that has behavior that is dependent on how the integrating framework and bundler implement it. If you are using this and just want your app to work, skip to the last paragraph of this comment.

---

Within the general feature scope of RSC, `SanityImage` is perfectly safe to treat as a server component, but only when it does not have a preview image as the `ImageWithPreview` component needs to listen to the `onLoad` event to swap images. Ideally, then, I could add `"use client"` to the `ImageWithPreview.tsx` file, or add a property to `SanityImage` like `SanityImage.server = true` to opt-in to this optimization, but [that's not the case](https://react.dev/blog/2023/03/22/react-labs-what-we-have-been-working-on-march-2023#react-server-components:~:text=Building%20your%20own,RSC%20built%2Din.).

Unfortunately, the current implementation in Next.js makes it difficult to actually support this feature due to a few problems:

1. esbuild strips the `"use client"` directive, treating it as a meaningless string
2. source files are bundled into a single file, meaning `SanityImage` would not be treated as a server component
3. users of `SanityImage` would not be able to import it into client components since [server components cannot be rendered in client components](https://nextjs.org/docs/getting-started/react-essentials#unsupported-pattern-importing-server-components-into-client-components)

I would welcome a PR that resolves these issues, treating `SanityImage` as a server component for those using it in server components and as a client component for those using it in client components without breaking the library for anybody else. As I understand it, though, this isn't straightforward to do.

The viable options I see are…

- Add `"use client"` to the top of the dist files, telling Next.js to treat it as it always has, explicitly opting out of optimization. This is bad because it will ostensibly change in the future and break apps.
- Remove support for preview images. This would be an unacceptable tradeoff.
- Find a way to support preview images without client side code. This is plausible to do with a CSS gradient generated from a blur hash, but only for images that are not transparent. Maybe there is another method?
- Refactor to make `ImageWithPreview` an explicit import that has to be passed to `SanityImage` as a prop. I would be okay with this if it only affected users that opted into this headache.
- Export a version of the library at a subpath for Next.js users (e.g., `sanity-image/client`). I don't love the idea of maintaining this, and while it works for now, it isn't any better than users adding `"use client"` to their wrapper.

\*climbs on soapbox\*

In my opinion, this feature remains extremely messy—it ships complexity, forces coupling, lacks backward compatibility, and fails to represent the real world use cases and needs of a substantial number of applications. I'm convinced that RSC and Next 13 should have initially treated existing code in the same way it has been by default, rendering both server and client side, at least until bundlers were able to catch up and support libraries that need to author both server and client components. While I don't want to discourage anybody from adopting RSC, I am not inclined to accept significant concessions in the ergonomics of using the library in order to support it, either.

This said, until there is a way to support RSC optimizations without unacceptable tradeoffs, my recommendation is as follows:

### For Next.js users using the `app` folder:

Add `"use client"` to your `Image` wrapper component. If you don't have one, I recommend you add one so you are not passing configuration in multiple places in your app anyways. [An example can be found in the README](https://github.com/coreyward/sanity-image#wrap-it-internally).

**Comment by markomitranic** [comment]
@coreyward some slight corrections - server components in React (not only next) are by no means bleeding edge at this point and are considered stabile. The only feature that is still not stabile is similarly named Server Actions, which caused a lot of confusion lately, and which is an opt-in feature, which has nothing to do with this ticket.

**To reiterate - this is not related to Next only, and definitely not "bleeding edge". It is pure React, and been stabile for a while now.**

Further, "enabling this feature" acutally means just simply stopping to use the limiting client-only primitives like react hooks. Stuff like useMemo, state, effect etc. No additional actions are needed, as soon as those are dropped from use. 

If they are noticed in a file, and imported into a server component, react will cry about it. If they aren't there, it will work on both server and client. While they might one day be an implementation that will be able to simulate these client-only APIs, there isn't one right now, and RSC are here to stay.

Thus, this leaves us with the goal - find a way to make the library more versatile by dropping client-only features like hooks. Easier said than done, of course, as the author has already pointed out, and potentially unneccesarry. I'll gladly look into how we can achieve that, can't promise anything, not a magician, but will try :) I would like to move that into a separate issue or PR tho, here is why...

--

Back to the original topic - my question actually has nothing to do with this :D What i was referring to is that the export of `buildSrc` is coming from the same namespace or file, that also includes a client-only component :P thus making the whole-ass file unusable in server components, even tho `buildSrc` should be perfectly safe to use as it is just a function. In fact, not only server components, but server code as well, like metadata generation functions, where I tried using them.

The way to resolve this would be to additionally allow import of this function from its file or separate namespace. 

Here is a good example, from a completely unrelated story:

1. For a long time people imported lodash as a whole `import _ from 'lodash';`
2. Then, they were told that it is not performant and they should select the parts they need `import { map, tail, times, uniq } from 'lodash';`
3. Finally, someone tested it and figured out that it still evaluates the whole lodash file, and in no way makes the bundle smaller. The currently correct way is: 
```ts
import map from 'lodash/map';
import tail from 'lodash/tail';
import times from 'lodash/times';
import uniq from 'lodash/uniq';
```

By allowing individual imports, it made the code uglier, but allowed to really evaluate less code. This is similar to what is happening in `sanity-image`. The import will evaluate the whole exported space, along with its limiting client-only components, for no reason. If we are importing a function we just need that function. So allowing an import like `import { buildSrc } from "sanity-image/utils";` would immediately resolve this issue, as the exporting module no longer has any client-only code.

**Comment by coreyward** [comment]
> server components in React (not only next) are by no means bleeding edge at this point and are considered stabile

RSC is stable insofar as the React team considers their portion of it stable. It is not actually released in a production/stable version of React, and the rest of the ecosystem around it is not stable. [From the horse’s mouth](https://react.dev/blog/2023/05/03/react-canaries#example-react-server-components) (from May 2023, currently the most recent blog post on the React blog):

<img width="979" alt="Screenshot 2023-06-29 at 3 46 23 PM" src="https://github.com/coreyward/sanity-image/assets/81224/423bd3bf-a414-4b62-a54f-7c2ecec6ecb5">

> Further, "enabling this feature" acutally means just simply stopping to use the limiting client-only primitives like react hooks. Stuff like useMemo, state, effect etc. No additional actions are needed, as soon as those are dropped from use.

Yeah, sure, all I have to do to save some portion of users a single, 3 second change is to remove behavior that is necessary for the operation of features that are well-established and popular. Why didn't I think of that?!

> The way to resolve this would be to additionally allow import of this function from its file or separate namespace.

Sure, the full dependency is loaded in server-only code, but all that happens is that functions are defined. And it's tiny. If someone is really only using `buildSrc` they still need roughly half of that code anyways. And as far as the browser is concerned, if you only import `buildSrc`, the rest of the package that isn't needed is able to be tree-shaken—feel free to run `agadoo` on it to verify, or check [Bundlephobia](https://bundlephobia.com/package/sanity-image@0.1.6).

> The import will evaluate the whole exported space, along with its limiting client-only components, for no reason. If we are importing a function we just need that function. So allowing an import like import { buildSrc } from "sanity-image/utils"; would immediately resolve this issue, as the exporting module no longer has any client-only code.

It's viable to add an additional generated file that is never used by the actual component being shipped (`SanityImage`) to enable this if that's what you're really looking for, but the following is false:

> Pure function evaluates useState for no reason, when using buildSrc

This implies `useState` is being called when using `buildSrc`. Look at the ESM output if you don't believe me—it's used once, inside of a function that is exported as `ImageWithPreview`. If you don't call that function or cause it to be called by calling the `SanityImage` function with a `preview` "prop", `useState` will never be called.

**Comment by markomitranic** [comment]
@coreyward 

> RSC is stable insofar as the React team considers their portion of it stable. It is not actually released in a production/stable version of React, and the rest of the ecosystem around it is not stable. [From the horse’s mouth](https://react.dev/blog/2023/05/03/react-canaries#example-react-server-components) (from May 2023, currently the most recent blog post on the React blog)

Call it what you will, the API is stable and won't change. Thus it is not bleeding edge. Just like the React team wrote in the attachment you posted. Is is not released, other than canary, but it is a stable API and has been for a while now. Canary's purpose is to allow the ecosystem, meaning library authors the time to adapt.

> Yeah, sure, all I have to do to save some portion of users a single, 3 second change is to remove behavior that is necessary for the operation of features that are well-established and popular. Why didn't I think of that?!

I don't appreciate the snarky answer. I'm trying to help here, give some insight as someone who has been using this stuff in production for a while now. Also, what I wrote is true, removing client side API usage would make it a server component. Is that what we actually want? Hell no.

> It's viable to add an additional generated file that is never used by the actual component being shipped (SanityImage) to enable this if that's what you're really looking for

Hmm I'm not sure I understand this part :/ I guess it is lingo that library authors are familiar with. From my limited knowledge, just keeping these utility functions in a separate file, and exporting them from there will do the trick.

> This implies useState is being called when using buildSrc. Look at the ESM output if you don't believe me—it's used once, inside of a function that is exported as ImageWithPreview. If you don't call that function or cause it to be called by calling the SanityImage function with a preview "prop", useState will never be called.

Sure, but what I believe more than ESM is the console log saying that it is in fact present :D As long as the same file exports both references, one of which uses client APIs, the whole file will be considered client-only it seems. Yes, even if you only import the function that in no way uses client APIs. 

I'll try to make a minimal example, to showcase this

**Comment by coreyward** [comment]
> Also, what I wrote is true, removing client side API usage would make it a server component. 

This isn't really the case. In very specific circumstances it could be rendered inside of a server component. In many others it would be rendered like a normal component, be that server side or client side.

> Sure, but what I believe more than ESM is the console log saying that it is in fact present :D As long as the same file exports both references, one of which uses client APIs, the whole file will be considered client-only it seems. Yes, even if you only import the function that in no way uses client APIs.

Yeah this is all pretty well [documented as part of how RSC works](https://github.com/reactjs/rfcs/blob/main/text/0227-server-module-conventions.md). If you have an actual solution that doesn't involve removing features, doesn't break the library for non-RSC users, and that works with a wide variety of bundlers, please do open a PR.

**Comment by markomitranic** [comment]
@coreyward same answer as in the other topic.

I have tested this locally, and I am telling you how it works. Whatever ESM or RSC spec say - this is how it works in practice. 

The solution is to simply export a submodule. And it works. I will open a PR.

**Comment by markomitranic** [comment]
@coreyward I can't open a PR because its 1AM and I need to sleep, and also still haven't figured out how to do submodule exports so i directly reference it inside `/dist`. I'll open a real PR over the coming days.

But, in the meantime here is a POC that works: https://github.com/markomitranic/sanity-image/commit/9174a6380636a6552243d41f86599968eb5d1411

By exporting only "universal" code in this submodule, we are able to then import it in another app, and because none of the files in the import tree ever depend on a platform specific hook, we are able to freely import it.

```ts
import { buildSrc } from "sanity-image/dist/utils"; 
import "server-only"; // added just for additional dose of proof, not needed

export default function Home() {
    return <>{buildSrc(sanityImage).src}</>;
}
```

I will provide a separate PR for the other issue, as this here is the only one I actually care about and have a solid use case for.

Just to make sure we are on the same page, an import like 
```ts
import { buildSrc } from "sanity-image"; 
import "server-only";
```

would fail the build step due to containing a server component.
