### ISSUE TITLE
`lqip` isn't being cropped by Sanity

### ISSUE THREAD

**Issue by markomitranic** [coreyward/sanity-image#35]
Previous Issues that seem related but don't really look into the lqip aspect ratio:

- https://github.com/coreyward/sanity-image/issues/22
- https://github.com/coreyward/sanity-image/issues/23

I was getting significant layout shift on some pages. When I disabled JS I discovered that image aspect ratios were all wrong. 

First I thought that width and height attributes are missing on previews, but then I realised that they aren't missing, and also that makes no difference, because the LQIP isn't the same size as the actual image.

- LQIP comes from Sanity, before the image URL is constructed by `sanity-image`, and thus it represents the full size image (unless image is cropped in Sanity).
- On the other hand, our URL gets constructed by `sanity-image` which adds `?auto=format&crop=entropy&fit=crop&h=350&q=85&w=350` to it.

So, we end up in a situation where LQIP doesn't really represent what the image will actually look like.
In my concrete example:

<img width="1123" alt="Screenshot 2023-07-08 at 10 31 45" src="https://github.com/coreyward/sanity-image/assets/10811624/5c9ddf14-b10e-4bb7-8821-7bbb60c119c4">

-- 

Now, this isn't really a `sanity-image` bug. We gave it data, and it did exactly what we expected it to. 

But I'm wondering if there is something we could do with the CSS surrounding the preview image, to basically center crop it. 
Or if there is a way for us to get an updated cropped LQIP possibly by fetching `&w=20&h=20`

**Comment by coreyward** [comment]
Since the LQIP is passed to `SanityImage` by the user, I’d consider the proposal to fetch the data independently to be out of scope for this library. Besides, fetching this data in the `SanityImage` component would mean fetching it client side over the network, which defeats the purpose of having a preview image. It is, of course, quite viable to generate low quality preview image data server-side and pass it as the `lqip` prop, and it's even viable to do so using the same logic as `SanityImage` with the `buildSrc` routine.

I think #23 covers the rest of what you've shared here. If you have thoughts re: the `aspect-ratio` solution, please share in that thread. Otherwise, I think the best workaround for the time being is to adjust the CSS.
