### ISSUE TITLE
Responsive Image hotspot not working

### ISSUE THREAD

**Issue by dvnrsn** [coreyward/sanity-image#47]
This is probably a question or a user error more than anything but I'm struggling to get this to work with a responsive image and could use some help.

In my case my image is restricted by an definitive height on parent but sometimes can be very wide and other times very narrow. my confusion is, even though I'm setting hot spot and crop in Sanity (and confirming they flow through), these are not being fully respected.

Sanity

![CleanShot 2024-06-25 at 23 11 47](https://github.com/coreyward/sanity-image/assets/9112811/70bce40e-fc1c-41d2-9a84-424e1181834e)

`<SanityImage`

![CleanShot 2024-06-25 at 23 12 27](https://github.com/coreyward/sanity-image/assets/9112811/de83a228-b74c-479f-8d44-f0c9c0a037a8)

```jsx
<div className="h-[200px] md:h-[400px] overflow-hidden">
    <SanityImageCorey
      id={firstPost.image?.asset?._ref}
      preview={firstPost.image?.blurDataURL}
      dataset={sanityDataset}
      projectId={sanityProjectID}
      hotspot={firstPost.image?.hotspot}
      crop={firstPost.image?.crop}
      className="max-w-full w-full h-auto"
    />
```

If I supply a height metric the image simply becomes blurred 🤔

**Comment by coreyward** [comment]
It looks like your CSS is setting an explicit height on the containing div and then hiding the overflow. It doesn't matter what you do with SanityImage, if you're rendering an image taller than 200px into this box without resizing the image in CSS it's going to overflow and be clipped.

If you don't think that's the issue, can you share the input values you're passing to SanityImage and the rendered HTML you are getting out? Or make a Codepen or CodeSandbox example?

**Comment by dvnrsn** [comment]
Thanks for the response. Given that I want the image to fill all available width but be maximally 400 or 200 pixels tall respectively, how would I configure SanityImage? Currently IIUC this is happening via the following CSS and of course an overflow: hidden which is undesired as you point out.

```css
img {
  max-width: 100%;
  height: auto;
```

Ok I think I figured it out for the most part. The only thing is `mode="cover"` does not apply `object-fit: cover` for me

```jsx
<SanityImage  
  className="max-h-[200px] md:max-h-[400px] object-cover"
  mode="cover"
  width={firstPost.image?.width}
  height={firstPost.image?.height}
/>

**Comment by coreyward** [comment]
For clarity, `SanityImage` does the work to request images from Sanity that align with the input you provide. It does not set any styles for you aside from the bare minimum required for the browser lazy loading to behave properly. This is by design—it lets developers control how they want images to be styled without having to learn/override/reset someone else’s opinionated styles, and it means your CSS is written in your app where it can be rendered/loaded however you've chosen.

The `mode` prop adjusts the way your `width` and `height` are interpreted:
- `contain` means those dimensions are treated as maximum boundaries to keep the full image within
- `cover` means the image needs to fill those dimensions and should be cropped to do so

For your case you need to consider the dimensions of images coming back from the Sanity API as well as the way the browser is rendering them. While it is possible to use a dynamic `width`, it's inefficient due to cache-misses and would clobber your Sanity bandwidth when users resize their viewport. So instead I recommend setting the `width` based on a reasonable target for the element. For the height, it's important to be cognizant of the aspect ratio changing as the containing element changes width. If your container is 1000px wide but only 200px tall, that's a 5:1 aspect ratio. If you resize the viewport down to 400px wide and still clamp the height to 200px, you're now showing the image at a 2:1 aspect ratio and you have 120k pixels being loaded but discarded by the browser. This might be better than the opposite, though—if you start with a 2:1 aspect ratio image that's 400x200, it'll have to be stretched significantly to fill the 1000px wide container on a larger screen, which will subsequently hide 120px of the original image height. Hopefully this is helpful context!

**Comment by dvnrsn** [comment]
Sorry to belabor the point here, but just to be sure I understand here, Corey.

In order for the hotspot to work, literal height and width must be supplied as well as `mode="cover"` (this I observe from [buildQueryParams](https://github.com/coreyward/sanity-image/blob/dfc3d20d1c2850089a91ee55fcd0385ea1dd965d/src/urlBuilder.ts#L213)). If I do this I am able to see the hotspot working its magic as I artificially manipulate `{x: 0.9, y: 0.9}`

This seemed restrictive to me as most of my images are dynamically rendered with `height: auto`, `width: 100%`. I was supplying the large width/height numbers that Sanity gives me. But if I simply supply the desired desktop viewport width/height and then let CSS max height do its magic, this responds quite nicely as I decrease the viewport width.

> It is possible to use a dynamic width

Here are you discouraging the approach of wrapping images with percentage widths or is this in reference to being able to provide a percentage as width to SanityImage? To me it sounds like you're referring to interacting with the imageUrlBuilder myself as SanityImage accepts only number for width, no?

**Comment by coreyward** [comment]
> In order for the hotspot to work, literal height and width must be supplied as well as `mode="cover"`

Yeah, if you think about what hotspot does this makes sense. Hotspot says "hey, if you have to change the aspect ratio of this image by cropping it, I want you to keep this specific point in the final image". Since `mode="contain"` doesn't ever crop the image, there's no opportunity for the hotspot to be applied.

> I was supplying the large width/height numbers that Sanity gives me. But if I simply supply the desired desktop viewport width/height and then let CSS max height do its magic, this responds quite nicely as I decrease the viewport width.

I'm not sure what you mean by this. The `width` prop should be set to a number that corresponds to the number of display pixels that the image is shown at in general. You probably want a number that reflects the largest common size, but that will vary based on your design. Then a `srcset` value will be generated automatically for you that includes both smaller and larger sizes, but the specific values of that will vary dependent on the original image and the requested size.

> To me it sounds like you're referring to interacting with the imageUrlBuilder myself as SanityImage accepts only number for width, no?

By "dynamic width" I mean that you can technically change the `width` prop value at any time and the output will update, just like any other normal React component. Typically this isn't needed, but in cases where the aspect ratio of an image changes dramatically depending on some state (or the viewport size) it can be beneficial to update the input props to align with the styled output. There is a performance penalty to doing this, though, so I recommend avoiding having more than a few values that get used, otherwise you wind up dynamically generating hundreds of URLs which will result in a precipitous drop in your cache-hit rate.

**Comment by dvnrsn** [comment]
What I meant is there is a width/height on the meta dimensions of the image in Sanity that I was querying for and then forwarding to SanityImage but that was effectively doing nothing. The approach that worked better for me is exactly as you say `a number that reflects the largest common size`. Thanks for your help and this component!

**Comment by coreyward** [comment]
Cool, glad I was able to help! 

For what it's worth, the original image width, height, and format are all encoded into the image ID. That's why SanityImage is able to reliably ensure that images larger than the original are never requested no matter what inputs you provide. 🙂
